/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as Sidebar_layoutRouteImport } from './routes/_sidebar_layout'
import { Route as Sidebar_layoutAboutRouteImport } from './routes/_sidebar_layout/about'
import { Route as Sidebar_layoutProjectsRouteImport } from './routes/_sidebar_layout/projects'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const Sidebar_layoutRoute = Sidebar_layoutRouteImport.update({
  id: '/_sidebar_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const Sidebar_layoutAboutRoute = Sidebar_layoutAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => Sidebar_layoutRoute,
} as any)
const Sidebar_layoutProjectsRoute = Sidebar_layoutProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => Sidebar_layoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof Sidebar_layoutAboutRoute
  '/projects': typeof Sidebar_layoutProjectsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof Sidebar_layoutAboutRoute
  '/projects': typeof Sidebar_layoutProjectsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_sidebar_layout': typeof Sidebar_layoutRouteWithChildren
  '/_sidebar_layout/about': typeof Sidebar_layoutAboutRoute
  '/_sidebar_layout/projects': typeof Sidebar_layoutProjectsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/projects'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/projects'
  id:
    | '__root__'
    | '/'
    | '/_sidebar_layout'
    | '/_sidebar_layout/about'
    | '/_sidebar_layout/projects'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  Sidebar_layoutRoute: typeof Sidebar_layoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_sidebar_layout': {
      id: '/_sidebar_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof Sidebar_layoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_sidebar_layout/about': {
      id: '/_sidebar_layout/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof Sidebar_layoutAboutRouteImport
      parentRoute: typeof Sidebar_layoutRoute
    }
    '/_sidebar_layout/projects': {
      id: '/_sidebar_layout/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof Sidebar_layoutProjectsRouteImport
      parentRoute: typeof Sidebar_layoutRoute
    }
  }
}

interface Sidebar_layoutRouteChildren {
  Sidebar_layoutAboutRoute: typeof Sidebar_layoutAboutRoute
  Sidebar_layoutProjectsRoute: typeof Sidebar_layoutProjectsRoute
}

const Sidebar_layoutRouteChildren: Sidebar_layoutRouteChildren = {
  Sidebar_layoutAboutRoute: Sidebar_layoutAboutRoute,
  Sidebar_layoutProjectsRoute: Sidebar_layoutProjectsRoute,
}

const Sidebar_layoutRouteWithChildren = Sidebar_layoutRoute._addFileChildren(
  Sidebar_layoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  Sidebar_layoutRoute: Sidebar_layoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
